### ISSUE TITLE
store tmp files in different folder

### ISSUE THREAD

**Issue by maxogden** [mafintosh/content-addressable-blob-store#8]
so when you kill a process the tmp files arent in the data folder as orphans

**Comment by bcomnes** [comment]
https://github.com/maxogden/temporary-directory

I might PR that.

**Comment by bcomnes** [comment]
Looks like maybe this is already done?  https://github.com/mafintosh/content-addressable-blob-store/blob/master/index.js#L100 

I'll have to do a deeper read to answer myself.  @mafintosh do you know?

**Comment by mafintosh** [comment]
@bcomnes seems we make a tmp dir and then simply do not use it hehe

**Comment by bcomnes** [comment]
Oh yeah Hrmm. I'll fix it
