### ISSUE TITLE
Return stat instead of boolean?

### ISSUE THREAD

**Issue by bcomnes** [mafintosh/content-addressable-blob-store#9]
I know this sounds weird, but I'm looking for a way to get real on-disk file path to blobs so that I can reference them with file URLs from an electron dom.  

It would be handy for the that.exists method to return the stat object instead of true so that I can access that info, when it exists.  Any issues with making a change like that?

**Comment by bcomnes** [comment]
Crap, stat objects don't have path info. >:[

**Comment by bcomnes** [comment]
Perhaps return a 3rd (or even 4th) argument? I just noticed ABS requires a boolean for `exists`.  Does it allow for coercion?

**Comment by mafintosh** [comment]
What abou adding a new method? .resolve perhaps?

**Comment by bcomnes** [comment]
I can work with that.  What should the callback be?  (err, path, stat)?

**Comment by bcomnes** [comment]
Actually, I don't even really need the stat right now, so just (err, path) is good enough for me.

**Comment by bcomnes** [comment]
From chat: `(err, path, stat)`  it is. Will PR today.
